name: "My action"
description: "test my action"

inputs:
  message:
    description: "The message to print"
    default: "Mundo!"
    required: true


runs:
  using: "composite"
  steps:
     - name: Hola Mundo
       run: echo "Hola ${{ inputs.message}}"
       shell: bash
