name: Example the Service 
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test
        run: ls

  

