name: Test Composite Action
on: [push]
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Local Action
        uses: ./.github/actions/my_action
       

  

