name: Example the Service 
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    env:
      MY_VAR: Mi variable de entorno

    steps:
      - name: ssh-password
        run: |
          mkdir -p  ~/.ssh
          echo "${{ secrets.SSH_KEY}}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

  

